#:schema https://mise.jdx.dev/schema/mise.json

[tool_alias]
nix = "https://github.com/mise-plugins/mise-nix.git"
# nix = "https://github.com/jbadeau/mise-nix.git"

[tools]
go = "latest"
node = "latest"
rust = "latest"
uv = "latest"
yq = "latest"
minikube = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
helm = "latest"
just = "latest"
flux2 = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
mc = "latest"
"go:github.com/abenz1267/gomvp" = "latest"
"go:github.com/isaacphi/mcp-language-server" = "latest"
"npm:mcp-hub" = "latest"
yarn = "latest"
"npm:typescript" = "latest"
"go:gotest.tools/gotestsum" = "latest"
"npm:@openapitools/openapi-generator-cli" = "latest"
"npm:@google/gemini-cli" = "latest"
pnpm = "latest"
"npm:nx" = "latest"
python = "3.13.12"
"pipx:markitdown" = { version = "latest", extras = "all" }

[tools."github:cloudnative-pg/cloudnative-pg"]
version = "latest"

[tools."github:cloudnative-pg/cloudnative-pg".platforms]
macos-arm64 = { asset_pattern = "kubectl-cnpg_{version}_darwin_arm64.tar.gz" }
macos-x64 = { asset_pattern = "kubectl-cnpg_{version}_darwin_x86_64.tar.gz" }
linux-x64 = { asset_pattern = "kubectl-cnpg_{version}_linux_x86_64.tar.gz" }
linux-arm64 = { asset_pattern = "kubectl-cnpg_{version}_linux_arm64.tar.gz" }
linux-ppc64le = { asset_pattern = "kubectl-cnpg_{version}_linux_ppc64le.tar.gz" }
linux-s390x = { asset_pattern = "kubectl-cnpg_{version}_linux_s390x.tar.gz" }
windows-x64 = { asset_pattern = "kubectl-cnpg_{version}_windows_x86_64.tar.gz" }
windows-arm64 = { asset_pattern = "kubectl-cnpg_{version}_windows_arm64.tar.gz" }

[tools."github:jonas-grgt/ktea"]
version = "latest"

[tools."github:jonas-grgt/ktea".platforms]
macos-arm64 = { asset_pattern = "ktea_{version}_darwin_arm64.tar.gz" }
macos-x64 = { asset_pattern = "ktea_{version}_darwin_amd64.tar.gz" }
linux-x64 = { asset_pattern = "ktea_{version}_linux_amd64.tar.gz" }
linux-arm64 = { asset_pattern = "ktea_{version}_linux_arm64.tar.gz" }
linux-armv7 = { asset_pattern = "ktea_{version}_linux_arm.tar.gz" }
windows-x64 = { asset_pattern = "ktea_{version}_windows_amd64.tar.gz" }
windows-arm64 = { asset_pattern = "ktea_{version}_windows_arm64.tar.gz" }

[tools."github:grafana/alloy"]
version = "latest"
rename_exe = "alloy"

[tools."github:grafana/alloy".platforms]
macos-arm64 = { asset_pattern = "alloy-darwin-arm64.zip" }
macos-x64 = { asset_pattern = "alloy-darwin-amd64.zip" }
linux-x64 = { asset_pattern = "alloy-linux-amd64.zip" }
linux-arm64 = { asset_pattern = "alloy-linux-arm64.zip" }
windows-x64 = { asset_pattern = "alloy-windows-amd64.exe.zip" }

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
pipx.uvx = true

[hooks]
enter = "mise i -q"
