#:schema https://mise.jdx.dev/schema/mise.json

[alias]
nix = "https://github.com/mise-plugins/mise-nix.git"
# nix = "https://github.com/jbadeau/mise-nix.git"

[tools]
go = "latest"
node = "latest"
rust = "latest"
uv = "latest"
yq = "latest"
minikube = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
helm = "latest"
just = "latest"
flux2 = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"
mc = "latest"
"go:github.com/abenz1267/gomvp" = "latest"
"go:github.com/isaacphi/mcp-language-server" = "latest"
"npm:mcp-hub" = "latest"
yarn = "latest"
"npm:typescript" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
pipx.uvx = true

[hooks]
enter = "mise i -q"
